/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2025-05-26 08:29:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FrmDangNhap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"Style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #0459ae;\">\r\n");
      out.write("\t<div class=\"slider mx-auto\">\r\n");
      out.write("\t<form style=\"background-color: white;\"  class=\"from-slider mx-auto border border-info-subtle border-5\" action=\"FrmDangNhap.jsp\" method=\"get\">\r\n");
      out.write("\t\t\t");
String tendn="";
			String mk="";	
		  tendn = request.getParameter("txtTenDn");
		  mk = request.getParameter("txtMk");
		  if(tendn==null)
			  tendn="";
		  if(mk==null)
			  mk="";
		  if(tendn.equals("abc") && mk.equals("123")){
			  response.sendRedirect("http://ums.husc.edu.vn");
		  }
		  else {
		  }
		
      out.write("\r\n");
      out.write("\t\t\t<img class=\"logo-img\" alt=\"\" src=\"https://student.husc.edu.vn/Themes/Login/images/logo-small.png\">\r\n");
      out.write("\t\t\t<h1 class=\"mb-2 pt-4\" style=\"color: #25258e; padding-left: 20px;\">SINH VIÊN:</h1>\r\n");
      out.write("\t\t\t<span style=\"display: flex;margin-left: 20px;margin-bottom: 5px;font-weight: bold;\">Mã sinh viên</span>\r\n");
      out.write("\t\t\t<input class=\"tendn mb-2 border border-light-subtle border-3\" style=\"border-radius:5px; text-indent: 10px;width: 270px;display:flex; position: relative; left: 20px; height: 40px\" type=\"text\" name=\"txtTenDn\" placeholder=\"Tên đăng nhập\" >\r\n");
      out.write("\t\t\t<span style=\"display: flex;margin-left: 20px;margin-bottom: 5px; font-weight: bold;\">Mật khẩu:</span>\r\n");
      out.write("\t\t\t<input class=\"mk border border-light-subtle border-3\" style=\"  border-radius:5px;width: 270px;position: relative;text-indent: 10px; left: 20px ; height: 40px\" type=\"text\" name=\"txtMk\" placeholder=\"Mật Khẩu\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary active\" type=\"submit\" name=\"dangnhap\" style=\" border-radius:5px;margin-left: 20px; margin-top: 25px;width: 270px;height: 40px;\">Đăng nhập</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
